# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField(max_length=400)),
                ('description', models.TextField()),
                ('extended', models.TextField()),
                ('meta', models.CharField(max_length=32, unique=True)),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('shared', models.BooleanField()),
                ('toread', models.BooleanField()),
                ('tags', models.TextField(blank=True)),
            ],
        ),
    ]
